language: python
python: 2.6
env: PLONE_VERSION=4.1 QA=true
matrix:
  include:
    - python: 2.7
      env: PLONE_VERSION=4.2
install:
  - sed -ie "s#travis-4.x.cfg#travis-$PLONE_VERSION.x.cfg#" travis.cfg
  - test "$PLONE_VERSION" = "4.1" && cat travis-4.1.x.cfg > travis.cfg || true
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -c travis.cfg annotate
  - bin/buildout -c travis.cfg -N -q -t 3
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: bin/test
after_success: test -n "$QA" && make coverage-validation python-validation || true
notifications:
  irc: irc.freenode.org#snmp-ve-dev
